name: Deploy VuePress site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # stable Node.js version
          cache: 'npm'

      # 3. Install project dependencies
      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      # 4. Ensure VuePress is executable
      - name: Fix permissions for VuePress
        run: chmod +x ./node_modules/.bin/vuepress || true

      # 5. Build the VuePress site
      - name: Build VuePress site
        run: npm run build

      # 6. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vuepress/dist
          # Optional: deploy from a branch other than main
          # publish_branch: gh-pages
