name: Deploy VuePress site

on:
  push:
    branches:
      - main   # Deploy whenever main branch is pushed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use a stable Node version

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Build the VuePress site
      - name: Build
        run: npm run build

      # 5. Deploy to GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vuepress/dist
